language: node_js
node_js:
- stable
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key:
    secure: NqkwDSurPmX6OP3p3qpSjfOQP8yhPiBxnSR40b9+MsAKLtGmlRGYxRpS/2Mh79mCgI/eOymPXRiFZ5JseAIF6tr/L33ArhmfPvmCw5NUIlsyuf3Gxprc3LMTEYubQ/PK9JiwjVaalxrUq/ZFuwyIeYIV5t0tFo3+bbunLD+2bVh3w3m180o/Zp8kNNnYxm33YDSvn50QW+tkmrGfZ1gp1buNJACdNBZMAtJxrq7MWgcHmkYpTrGiJJLACy14cU5PWAbyaKdKszC5tzy2J/IH2W7aRbaF5covLbnVbSPknvl9NoROOgPUNLascobdNjsnEdLdVg+mAIF1euylTr7t1LNc38qlwkhxx6PE8MHfcG1gqTcYR3H5lew18de+EPwNwK6y3nXDnNEnu4hSqvHsSALvhDhRJpxM1upUho75uBfzFM8HgdwWGkw/OUmzm2H9bLhCttQEv9TLSvFDin9kfewLFHMopz+NcLmRVibto8i+QU7QoI1dwqZKqNkkCH/ZaA5HMver5qlzCa7ZIfOssulUJ97bYV6P9u139IQb4XqSgAVJ9nlQ1GrAejOUV4+zTkX6uWK0DVa9H3aHEUTn/0HKg6DuCRio7DvFIIXk6MzpHSRvz4B2lGVWorZ9v3+q1IH8E/7BHRaRFJMXjz5v+QaZLB0L+apsEZxSG/KMMPU=
  on:
    tags: true
    repo: uraniumreza/ongko
    branch: master
