language: node_js
node_js:
  - stable
install:
  - npm install
script:
  - npm test
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_token:
    secure: fgZApJHSwxZt5uxLnv+mOD9NqLtZSafmwwZFhpRIb/Xr6KUBstdxjMHaaWAwkHNEhkXFWWyHqqM6Ztzqi319yZ2S3a7mcSXeg2RSxfDS0G9uHu7YYbUSO7xuMQR/X9/BCe/9lOx5LhwEXuT7qfHyteHuZcZThCmvMC2A4lCWm2iJip+aFQMPieptLXH/oQt1UEBe7etSZClBOPJLDuwAi7mKoSLJLlU/6FXQm+yKDkI4IKMqcuG5YSu/M/AEuGTYWGEZaWDmSTPAQxwLe7Gzj1QHDZm7IVfVFrJcBlxibE+6uh0hc9x/JZAbuMmsMwN+epjB4SotiHNrXXW7SRyJOdMIh6oeN+J+/MumMQhe10T7mDwlFpVvih4jnC5sMLsVB9BFRFXk+bkZNGZ/AI84Uq+SWfJVeA2QZfIZpu+24FVar+N1frViXs/s3cM0u5JGdMNwMwOiWYzSlskXpJ7otutjgksXy+hhvMGQulL4KwS8BmU2NuNM6YmYWbI541xAzprFju21DQc6bSm0nDnEkAtV+E3EYWvUzZjsJR17OEl6ggyJ+R+lHRUa6ENyCg1a9dMVhwEHkIs3Qu2mTBMkatdv4q0I+rdOlnI/XpmRwx4fKc3PWmrvXhYmm8gqJp5oN7vxcOzs1RoRRrHgvy5/0TreVYZdVeZur2FUxPuKUns=
  on:
    tags: true
    repo: uraniumreza/ongko
    branch: master
